#!/bin/bash
# Used for OftenDeck. Last updated 2025.04.24

echo "Starting battery saving mode..."

SERVICES=(
  bluetooth
  avahi-daemon
  cron
  ModemManager
  NetworkManager
#  nmbd # Samba Daemon for file and printer sharing
#  smbd # NetBIOS Name Service Daemon used for Windows OS to find Linux Server
  systemd-timesyncd
  triggerhappy
  wpa_supplicant
  exim4
)

for S in "${SERVICES[@]}"; do
  echo "Stopping $S..."
  sudo systemctl stop "$S"
#  sudo systemctl disable "$S" # This saves settings after boot. This was once once during installation and then commented out.
done

echo "Battery saving mode is active."
