#!/bin/bash

# Start networking services
echo "Starting networking services..."
often-battery-mode-off > /dev/null 2>&1
# sudo nmcli device wifi hotspot ssid microjournal password microjournal ifname wlan0

# Start dufs and syncthing in the background
cd /home/oftendeck/documents/
/home/oftendeck/.cargo/bin/dufs -A > /dev/null 2>&1 &  # Run dufs silently in the background
DUFS_PID=$!  # Get the PID of dufs

syncthing > /dev/null 2>&1 &  # Run syncthing in the background
SYNCTHING_PID=$!  # Get the PID of syncthing

# Get the IP address of the machine
IP_ADDRESS=$(hostname -I | awk '{print $1}')

# Display the URLs for Syncthing and Dufs
echo "#########################################################"
echo "To connect to Syncthing, use: http://$IP_ADDRESS:8384/"
echo "To connect to Dufs, use: http://$IP_ADDRESS:5000/"
echo "#########################################################"

# Trap Ctrl+C and kill both processes, then stop the network
trap 'kill $DUFS_PID $SYNCTHING_PID; echo "Stopping dufs and syncthing..."; \
      echo "Re-Enabling Battery Saving Mode"; \
      often-battery-mode-on \
      exit' SIGINT

# Wait indefinitely to keep the script running
wait