#!/bin/bash
# Used for OftenDeck. Last updated 2025.04.24

# Get the current date in YYYYMMDD format
today=$(date +%Y%m%d)

# Define the path once
img="/mnt/backups/oftendeck${today}.img"

# Step 1: Create the backup image
sudo image-backup --initial "$img"

# Step 2: Shrink the same image
sudo image-shrink "$img"
